legacy: Add vlc handler
getsolus/usysconf pull request #18
Opened 2024-04-20 22:54 UTC by ReillyBrogan

Given that we're not yet migrated to the go usysconf we might as well add a VLC plugins cache since we're using VLC as the phonon provider on Plasma.

2024-05-14 07:17 UTC, ermo commented
@EbonJaeger I've tentatively added you as a reviewer, given your C experience.

2024-05-14 16:37 UTC, EbonJaeger requested changes
Only one thing that I can see.

2024-05-14 16:37 UTC, EbonJaeger commented on src/handlers/vlc.c
> +static UscHandlerStatus usc_handler_vlc_exec(__usc_unused__ UscContext *ctx, const char *path)
`ctx` does appear to actually be used.
```suggestion
static UscHandlerStatus usc_handler_vlc_exec(UscContext *ctx, const char *path)
```

2026-03-13 16:04 UTC, EbonJaeger approved these changes
LGTM, thanks!

2026-03-13 16:04 UTC, merged